config/routes.rb
Rails.application.routes.draw do

  # Root
  root to: 'visitors#index'

  # Users:
  devise_for :users
  resources :users
  get '/dashboard/:id', to: 'users#dashboard', as: 'dashboard'

  # Conversations:
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
        where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  after_create :create_droid_response, if: Proc.new { |message| message.conversation_recipient.is_droid? }

  def create_droid_response
    Message.skip_callback(:create, :after, :create_droid_response)
    Message.create(body: gather_droid_response, user_id: droid_responder_id, conversation_id: conversation.id)
    Message.set_callback(:create, :after, :create_droid_response)
  end

  def gather_droid_response
    conversation_recipient.random_droid_response
  end

  def conversation_recipient
    conversation.recipient
  end

  def droid_responder_id
    conversation_recipient.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Relationships:
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :conversations, foreign_key: :recipient_id

  # Callbacks:
  after_create :create_conversation_with_yoda, unless: Proc.new { |user| user.admin? }

  def create_conversation_with_yoda
    @yoda = User.find_yoda
    conversation = Conversation.create(recipient_id: self.id, sender_id:  @yoda.id)
    Message.create(body: @yoda.quote, user_id: @yoda.id, conversation_id: conversation.id)
  end

  def self.find_yoda
    find_by(name: "Yoda")
  end

  def self.select_droids
    where("admin = (?) AND name != (?)", true, "Yoda")
  end

  def is_droid?
    self.admin? && name != "Yoda"
  end

  def random_droid_response
    quote = self.quote
    return quote if name == 'C-3PO'
    quote.slice(rand(quote.size), rand(quote.size) +1).strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    dashboard_path(current_user)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])

    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])

    session[:conversations].delete(@conversation.id)

    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :dashboard]
  before_action :check_user_rights, only: [:dashboard, :index, :show]

  def index
    @users = User.all
  end

  def show
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def dashboard
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                         .find(session[:conversations])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_user_rights
    redirect_to root_path if current_user != set_user
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @droids = User.select_droids
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def admin_image_helper(name)
    "admin/#{name.downcase}.png"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def hobbies
    @hobbies = [1, 2, 3, 4, 5, 6]
  end

end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.opposed_user(user).name, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>

    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <form class="new_message">
        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
        <textarea name="body" class="form-control"></textarea>
        <input type="submit" class="btn btn-send" value="Send">
      </form>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
    <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
    conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
    conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 text-center">
      <p class="small">A PRODUCT OF</p>
      <h4><%= image_tag('branding/logo_black_text.png') %>
      </h4>
      <p>3344 Walnut St<br>Denver, CO 80205</p>
      <ul class="list-unstyled">
        <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">support@starchat.com</a>
        </li>
      </ul>
      <br>
      <ul class="list-inline">
        <li>
          <a href="https://facebook.com/BiggerPockets"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
        </li>
        <li>
          <a href="http://twitter.com/biggerpockets"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/company-beta/804252/"><i class="fa fa-youtube fa-fw fa-3x"></i></a>
        </li>
        <li>
          <a href="https://www.youtube.com/user/BiggerPockets"><i class="fa fa-linkedin fa-fw fa-3x"></i></a>
        </li>
      </ul>
      <hr class="small">
      <p class="text-muted">Copyright &copy; Bigger Pockets 2079</p>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div id="alert-notice" class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="header" class="navbar navbar-white navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('branding/logo_black_text.png'), root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Home', root_path, method: :get %></li>
<% if user_signed_in? %>
    <li><%= link_to 'Users', users_path, method: :get if current_user.admin? %></li>
    <li><%= link_to 'Dashboard', dashboard_path(current_user), method: :get %></li>
    <li><%= link_to 'Edit account', edit_user_registration_path, method: :get %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path, method: :get %></li>
    <li><%= link_to 'Sign up', new_user_registration_path, method: :get %></li>
<% end %>

app/views/layouts/_sidebar_nav.html.erb
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
    <li class="sidebar-brand">
      <a href="#top" onclick=$("#menu-close").click();><%= inline_svg 'branding/logo-pocket.svg', class: 'logo-header' %></a>
    </li>
    <%= render 'layouts/navigation_links' %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Star Chat" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Star Chat" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Custom Fonts -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body class="<%= controller_name %> <%= action_name %>">
<header>
  <%= render 'layouts/messages' %>
  <%= render 'layouts/sidebar_nav' %>
  <%= render 'layouts/navigation' unless current_page?(root_path) %>
</header>
<div id="<%= controller_name %>-<%= action_name %>" class="<%= "page-container" unless controller_name == "visitors" %>">
  <%= yield %>
</div>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>

app/views/users/_droid.html.erb
<div class="col-md-3 col-sm-6">
  <div class="service-item">
    <%= image_tag("#{ admin_image_helper(droid.name) }", class: 'droid-img') %>
    <h4>
      <strong><%= droid.name %></strong>
    </h4>
    <%= link_to "CHAT NOW", new_user_registration_path, class: 'btn btn-light', method: :get %>
  </div>
</div>

app/views/users/_user.html.erb
<tr>
  <th>
    <% if user.admin? %>
        <%= image_tag("#{ admin_image_helper(user.name) }", class: 'thumb-img') %>
    <% end %>
  </th>
  <th><%= link_to user.name, conversations_path(user_id: user), remote: true, method: :post %></th>
  <th class="user-role text-right <%= "admin-role" if user.admin? %>"><%= user.admin? ? "ACTIVE SUPPORT" : "HUMAN" %></th>
</tr>

app/views/users/dashboard.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="thumbnail">
      <br>

      <table class="full-width table table-hover">
        <%= render(@users.reverse) %>
      </table>
    </div>
  </div>
  <div class="col-sm-8">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
          <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/_hobby.html.erb
<div class="col-md-6">
  <div class="more-time-background-image" style="background-image: url(<%= asset_path "visitors/more_time_#{hobby}.jpg" %>); background-position: center;"></div>
</div>

app/views/visitors/index.html.erb
<!-- Hero -->
<header id="top" class="hero">
  <div class="text-vertical-center">
    <h1><a href="https://www.biggerpockets.com/"><%= inline_svg 'branding/logo-pocket.svg', class: 'logo-header' %></a>
    </h1>
    <p>PRESENTS</p>
    <h3>STAR CHAT</h3>
    <br>
    <%= link_to "CHAT NOW", new_user_registration_path, class: 'btn btn-dark btn-lg', method: :get %>
  </div>
</header>

<!-- About -->
<section id="about" class="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Asynchronous Chat with someone in a galaxy far, far away....</h2>
        <p class="lead">faster than a new version of anything by Microsoft needing to be patched</p>
        <p class="small">POWERED BY</p>
        <p>Action Cable</p>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

<!-- support -->
<!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
<section id="support" class="support bg-primary">
  <div class="container">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2>Chat with galaxy-class droid support</h2>
        <hr class="small">
        <div class="row">
          <%= render partial: 'users/droid', collection: @droids %>
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.col-lg-10 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

<!-- Callout -->
<aside class="callout">
  <div class="text-vertical-center">
    <h1 class="text-center">Save Time for the Important<br>Things in Life</h1>
    <hr class="small">
  </div>
</aside>

<!-- Save Time -->
<section id="save-time" class="save-time">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 text-center">
        <div class="row">
          <%= render partial: 'visitors/hobby', collection: hobbies %>
        </div>
        <!-- /.row (nested) -->
        <%= link_to "CHAT NOW", new_user_registration_path, class: 'btn btn-dark btn-lg', method: :get %>
      </div>
      <!-- /.col-lg-10 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

<!-- Call to Action -->
<aside class="call-to-action bg-primary">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3>HEAD QUARTERED IN DENVER, COLORAD0, USA, EARTH</h3>
      </div>
    </div>
  </div>
</aside>

<!-- Map -->
<section id="contact" class="map">
  <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3066.8203679120816!2d-104.97928358462379!3d39.766141379446026!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x876c7e982447d593%3A0x418481f89e7c19d!2sBiggerPockets%2C+Inc.!5e0!3m2!1sen!2sus!4v1506807943164"></iframe>
  <br/>
  <small>

    <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3066.8203679120816!2d-104.97928358462379!3d39.766141379446026!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x876c7e982447d593%3A0x418481f89e7c19d!2sBiggerPockets%2C+Inc.!5e0!3m2!1sen!2sus!4v1506807943164"></a>
  </small>
  </iframe>
</section>